"""Orbits must be orbits, whether the caller hands over a group or generators.

`orbit(node, group)` applied each supplied permutation once. That is the orbit
when `group` is every element of the group and the one-step image set otherwise,
and `PermutationGroup.generators` is a public attribute holding exactly the
otherwise. Under the cyclic group generated by `(0 1 2 3 4)` the orbit of node 0
is all five nodes and it returned `{1}`; `all_orbits` then left nodes in no block
at all despite being documented as a partition, and `quotient_by_symmetry` died
on the missing key.

The group results are checked against invariants rather than against a second
implementation: the orbit-stabilizer theorem, Lagrange, and that orbits
partition. A bug in the closure, the stabilizer or the orbit breaks one of them,
and none of the three needs the right answer known in advance.

Run as a whole against the unfixed source, 13 of these 42 fail and the rest pass
either way. The ones that pass are not offered as evidence of the fix; they are
kept as regression guards. The reason they cannot discriminate is itself the
reason the defect survived: `find_apg_automorphisms` returns a group whose
`generators` attribute holds *every element*, so a test routed through it is
taking the full-group path under a generating-set name. A group does generate
itself, so this is correct and not a defect -- but it means the repo's own tests
never exercised the case that was broken. The tests that do discriminate build a
genuine two-element generating set with `symmetric_on_leaves`, or use a single
5-cycle.
"""

from __future__ import annotations

import itertools
import math

import pytest

from grounded_hyperset_theory import AccessiblePointedGraph, Node
from grounded_hyperset_theory.hyper_calculus import (
    Permutation,
    PermutationGroup,
    all_orbits,
    automorphism_group,
    find_apg_automorphisms,
    orbit,
    quotient_by_symmetry,
)


def star(k: int) -> AccessiblePointedGraph:
    """A root with k leaves. Its pointed automorphism group is S_k on the leaves."""
    return AccessiblePointedGraph(
        root=0,
        edges={0: list(range(1, k + 1)), **{i: [] for i in range(1, k + 1)}},
    )


def directed_cycle(n: int) -> AccessiblePointedGraph:
    """A directed n-cycle. Fixing the root leaves only the identity."""
    return AccessiblePointedGraph(root=0, edges={i: [(i + 1) % n] for i in range(n)})


def rotation(n: int) -> Permutation:
    """The n-cycle (0 1 ... n-1) as a permutation of Node(0) .. Node(n-1)."""
    nodes = [Node(i) for i in range(n)]
    return Permutation({nodes[i]: nodes[(i + 1) % n] for i in range(n)})


def symmetric_on_leaves(k: int) -> PermutationGroup:
    """S_k on the leaves 1..k of star(k), from two generators, with the root fixed.

    A transposition and a k-cycle generate the full symmetric group, so this is
    the same group `find_apg_automorphisms(star(k), pointed=True)` returns -- but
    from an actual generating set of size 2 rather than from all k! elements.
    That distinction is the whole subject of this file, so the invariant tests
    that go through `generators` use this and not the automorphism search.
    """
    leaves = [Node(i) for i in range(1, k + 1)]
    root = {Node(0): Node(0)}
    swap = Permutation({**root, **{leaves[0]: leaves[1], leaves[1]: leaves[0]},
                        **{leaf: leaf for leaf in leaves[2:]}})
    cycle = Permutation({**root, **{leaves[i]: leaves[(i + 1) % k] for i in range(k)}})
    return PermutationGroup([swap] if k == 2 else [swap, cycle])


# ============================================================================
# 1. A generating set gives the same orbit as the whole group
# ============================================================================


def test_the_orbit_under_a_single_generator_is_the_whole_cycle() -> None:
    # The central case. One generator, five nodes, and applying it once reaches
    # exactly one of them.
    group = PermutationGroup([rotation(5)])
    assert group.order == 5
    assert len(group.generators) == 1
    assert orbit(Node(0), group.generators) == {Node(i) for i in range(5)}


def test_generators_and_elements_give_the_same_orbit() -> None:
    group = PermutationGroup([rotation(5)])
    for node in group.domain:
        assert orbit(node, group.generators) == orbit(node, group.elements())


def test_a_two_generator_group_agrees_with_its_closure() -> None:
    nodes = [Node(i) for i in range(5)]
    swap = Permutation({nodes[0]: nodes[1], nodes[1]: nodes[0],
                        nodes[2]: nodes[2], nodes[3]: nodes[3], nodes[4]: nodes[4]})
    group = PermutationGroup([rotation(5), swap])
    assert group.order == 120, "the 5-cycle and a transposition generate S_5"
    for node in group.domain:
        assert orbit(node, group.generators) == orbit(node, group.elements())
        assert orbit(node, group.generators) == set(nodes)


def test_a_point_is_in_its_own_orbit() -> None:
    group = PermutationGroup([rotation(4)])
    for node in group.domain:
        assert node in orbit(node, group.generators)


def test_negative_control_applying_each_generator_once_is_not_the_orbit() -> None:
    # The replaced body. Kept so the gap stays legible.
    group = PermutationGroup([rotation(5)])
    one_step = {g.apply(Node(0)) for g in group.generators}
    assert one_step == {Node(1)}, "one application of the single generator"
    assert one_step != orbit(Node(0), group.generators)


# ============================================================================
# 2. all_orbits is a partition
# ============================================================================


@pytest.mark.parametrize("k", [2, 3, 4, 5])
def test_orbits_cover_every_node_and_are_disjoint(k: int) -> None:
    apg = star(k)
    group = find_apg_automorphisms(apg, pointed=True)
    for permutations in (symmetric_on_leaves(k).generators, group.elements()):
        blocks = all_orbits(apg, permutations)
        assert set().union(*blocks) == set(apg.nodes)
        assert all(not (a & b) for a, b in itertools.combinations(blocks, 2))


def test_a_partition_holds_for_a_generating_set_that_misses_nodes_in_one_step() -> None:
    apg = AccessiblePointedGraph(root=0, edges={0: [1, 2, 3, 4], **{i: [] for i in range(1, 5)}})
    group = PermutationGroup([rotation(5)])
    blocks = all_orbits(apg, group.generators)
    assert blocks == [{Node(i) for i in range(5)}]
    assert set().union(*blocks) == set(apg.nodes)


def test_negative_control_one_step_images_left_nodes_unblocked() -> None:
    # The replaced body, reproduced. Two of five nodes ended up in no block, and
    # a quotient over that is not defined.
    apg = AccessiblePointedGraph(root=0, edges={0: [1, 2, 3, 4], **{i: [] for i in range(1, 5)}})
    permutations = list(PermutationGroup([rotation(5)]).generators)
    target = set(apg.nodes)
    visited: set[Node] = set()
    blocks: list[set[Node]] = []
    for n in sorted(target, key=lambda x: str(x.id)):
        if n not in visited:
            block = {g.apply(n) for g in permutations if g.apply(n) in target}
            visited.update(block)
            blocks.append(block)
    assert set().union(*blocks) != target, "the blocks did not cover the graph"


def test_the_star_collapses_its_leaves_into_one_block() -> None:
    apg = star(4)
    group = find_apg_automorphisms(apg, pointed=True)
    blocks = all_orbits(apg, group.elements())
    assert sorted(len(b) for b in blocks) == [1, 4], "the root alone, and the four leaves"


def test_a_directed_cycle_has_only_singleton_orbits_when_pointed() -> None:
    apg = directed_cycle(5)
    group = find_apg_automorphisms(apg, pointed=True)
    assert group.order == 1
    assert all(len(b) == 1 for b in all_orbits(apg, group.elements()))


# ============================================================================
# 3. quotient_by_symmetry
# ============================================================================


def test_the_quotient_is_the_same_from_generators_or_from_the_group() -> None:
    apg = star(4)
    group = find_apg_automorphisms(apg, pointed=True)
    from_generators = quotient_by_symmetry(apg, group.generators)
    from_elements = quotient_by_symmetry(apg, group.elements())
    assert len(from_generators.nodes) == len(from_elements.nodes)
    assert from_generators.edge_count == from_elements.edge_count


def test_quotienting_the_star_gives_a_root_and_one_leaf_block() -> None:
    apg = star(4)
    group = find_apg_automorphisms(apg, pointed=True)
    quotient = quotient_by_symmetry(apg, group.elements())
    assert len(quotient.nodes) == 2


def test_a_generating_set_no_longer_crashes_the_quotient() -> None:
    # This raised KeyError out of an internal dict.
    apg = AccessiblePointedGraph(root=0, edges={0: [1, 2, 3, 4], **{i: [] for i in range(1, 5)}})
    quotient = quotient_by_symmetry(apg, PermutationGroup([rotation(5)]).generators)
    assert len(quotient.nodes) == 1


def test_the_trivial_group_leaves_the_graph_alone() -> None:
    apg = directed_cycle(4)
    group = find_apg_automorphisms(apg, pointed=True)
    quotient = quotient_by_symmetry(apg, group.elements())
    assert len(quotient.nodes) == len(apg.nodes)


# ============================================================================
# 4. Group-theoretic invariants, which need no reference implementation
# ============================================================================


@pytest.mark.parametrize("k", [2, 3, 4, 5])
def test_orbit_stabilizer_holds_for_every_node(k: int) -> None:
    # |G| = |orbit(x)| * |stabilizer(x)|. Breaks if the closure, the orbit or the
    # stabilizer is wrong, without the answer being known in advance.
    group = find_apg_automorphisms(star(k), pointed=True)
    for node in group.domain:
        assert len(orbit(node, group.elements())) * group.stabilizer(node).order == group.order


@pytest.mark.parametrize("k", [2, 3, 4, 5])
def test_orbit_stabilizer_holds_through_a_real_generating_set(k: int) -> None:
    # Two generators, k! elements. This is the route that was broken: the orbit
    # of a leaf came back as the one or two leaves a single generator moved it
    # to, so |orbit| * |stab| undershot |G| by the whole factor it was missing.
    group = symmetric_on_leaves(k)
    assert group.order == math.factorial(k)
    assert len(group.generators) <= 2
    for node in group.domain:
        assert len(orbit(node, group.generators)) * group.stabilizer(node).order == group.order


@pytest.mark.parametrize("k", [2, 3, 4, 5])
def test_lagrange_the_stabilizer_order_divides_the_group_order(k: int) -> None:
    group = find_apg_automorphisms(star(k), pointed=True)
    for node in group.domain:
        assert group.order % group.stabilizer(node).order == 0


# ============================================================================
# 5. The automorphism counts themselves
# ============================================================================


@pytest.mark.parametrize("k, factorial", [(2, 2), (3, 6), (4, 24), (5, 120), (6, 720)])
def test_a_star_has_k_factorial_pointed_automorphisms(k: int, factorial: int) -> None:
    # The root is fixed and the leaves are interchangeable, so Aut is S_k.
    assert len(automorphism_group(star(k), pointed=True)) == factorial


@pytest.mark.parametrize("n", [3, 4, 5, 7])
def test_a_pointed_directed_cycle_has_only_the_identity(n: int) -> None:
    # Fixing the root fixes its successor, and so on around the cycle.
    assert len(automorphism_group(directed_cycle(n), pointed=True)) == 1


def test_every_returned_automorphism_fixes_the_root_and_preserves_edges() -> None:
    apg = star(4)
    root = Node(0)
    for auto in automorphism_group(apg, pointed=True):
        assert auto.apply(root) == root
        for u in apg.nodes:
            assert {auto.apply(v) for v in apg.children(u)} == apg.children(auto.apply(u))


def test_the_automorphisms_form_a_group_closed_under_composition() -> None:
    group = find_apg_automorphisms(star(4), pointed=True)
    elements = group.elements()
    assert all(a * b in group for a in elements for b in elements)
    assert all(~a in group for a in elements)


def test_the_automorphism_search_returns_every_element_as_a_generator() -> None:
    # Not a defect -- a group generates itself -- but worth pinning, because it
    # is why every existing test of `orbit` took the full-group path and the
    # generating-set path stayed unexercised until it broke.
    for k in (3, 4, 5):
        group = find_apg_automorphisms(star(k), pointed=True)
        assert set(group.generators) == set(group.elements())
        assert len(group.generators) == math.factorial(k)


def test_a_group_of_prime_order_is_abelian_and_a_symmetric_one_is_not() -> None:
    assert PermutationGroup([rotation(5)]).is_abelian() is True
    nodes = [Node(i) for i in range(5)]
    swap = Permutation({nodes[0]: nodes[1], nodes[1]: nodes[0],
                        nodes[2]: nodes[2], nodes[3]: nodes[3], nodes[4]: nodes[4]})
    assert PermutationGroup([rotation(5), swap]).is_abelian() is False
