"""Grounded Hyperset Theory.

Accessible Pointed Graphs, non-well-founded sets, constructive membership,
meta-calculi, hyper-calculi, language calculi, and real analysis bridges.
"""

from __future__ import annotations

from .abstraction import (
    AbstractionMapping,
    NodePartition,
    depth_abstract_hyperset,
    depth_abstraction,
    is_bisimulation_congruence,
    is_congruence,
    predicate_abstract_hyperset,
    predicate_abstraction,
    quotient_apg,
    quotient_hyperset,
    refine_to_bisimulation,
    scc_abstract_hyperset,
    scc_quotient,
)
from .graph import AccessiblePointedGraph, Node
from .hyper_calculus import (
    Permutation,
    PermutationGroup,
    cyclic_group,
    discrete_derivative,
    find_apg_automorphisms,
    find_hyperset_automorphisms,
    is_apg_automorphism,
    is_invariant_under,
    orbit_quotient_apg,
    orbit_quotient_hyperset,
    trivial_group,
)
from .hyperset import (
    EmptyHyperset,
    Hyperset,
    QuineAtom,
    bisimilar,
    ordinal_add,
    ordinal_mul,
    ordinal_pow,
    pair,
    solve_system,
    von_neumann_ordinal,
)
from .language_calculus import (
    FormalGrammar,
    ProductionRule,
    Regex,
    SyntaxTerm,
    dfa_apg,
    dfa_hyperset,
    grammar_bisimilar,
    liar_sentence,
    quine_syntax_term,
    self_referential_term,
    string_to_hyperset,
    symbol_to_hyperset,
    syntax_bisimilar,
    truth_teller_sentence,
)
from .meta_calculus import (
    RewriteRule,
    RewriteSystem,
    build_trajectory_apg,
    create_hyperset_rewrite_system,
    find_periodic_orbits,
    is_locally_confluent,
    is_terminating,
    normal_forms,
    trajectory_bisimilar,
    trajectory_hyperset,
)
from .real_analysis_bridge import (
    CauchySequence,
    DedekindCut,
    GroundedInteger,
    GroundedRational,
    SurrealNumber,
    are_equivalent_cauchy,
    derivative_quotient,
    riemann_integral,
    symbolic_polynomial_derivative,
    symbolic_polynomial_integral,
)
from .meta import (
    Abstraction,
    abstract,
    deobjectify_apg,
    deobjectify_function,
    deobjectify_relation,
    fractal_hyperset,
    meta_fractalize,
    objectify_apg,
    objectify_function,
    objectify_relation,
    unfold_step,
)

__version__ = "0.2.0"

__all__ = [
    # Core APG and Hyperset
    "AccessiblePointedGraph",
    "EmptyHyperset",
    "Hyperset",
    "Node",
    "QuineAtom",
    "bisimilar",
    "ordinal_add",
    "ordinal_mul",
    "ordinal_pow",
    "pair",
    "solve_system",
    "von_neumann_ordinal",
    # Abstraction
    "AbstractionMapping",
    "NodePartition",
    "depth_abstract_hyperset",
    "depth_abstraction",
    "is_bisimulation_congruence",
    "is_congruence",
    "predicate_abstract_hyperset",
    "predicate_abstraction",
    "quotient_apg",
    "quotient_hyperset",
    "refine_to_bisimulation",
    "scc_abstract_hyperset",
    "scc_quotient",
    # Meta Calculus (Symbolic Dynamics)
    "RewriteRule",
    "RewriteSystem",
    "build_trajectory_apg",
    "create_hyperset_rewrite_system",
    "find_periodic_orbits",
    "is_locally_confluent",
    "is_terminating",
    "normal_forms",
    "trajectory_bisimilar",
    "trajectory_hyperset",
    # Hyper Calculus (Group Theory & Automorphisms)
    "Permutation",
    "PermutationGroup",
    "cyclic_group",
    "discrete_derivative",
    "find_apg_automorphisms",
    "find_hyperset_automorphisms",
    "is_apg_automorphism",
    "is_invariant_under",
    "orbit_quotient_apg",
    "orbit_quotient_hyperset",
    "trivial_group",
    # Language Calculus (Formal Syntax & Grammars)
    "FormalGrammar",
    "ProductionRule",
    "Regex",
    "SyntaxTerm",
    "dfa_apg",
    "dfa_hyperset",
    "grammar_bisimilar",
    "liar_sentence",
    "quine_syntax_term",
    "self_referential_term",
    "string_to_hyperset",
    "symbol_to_hyperset",
    "syntax_bisimilar",
    "truth_teller_sentence",
    # Real Analysis Bridge (Classical Calculus Reachability)
    "CauchySequence",
    "DedekindCut",
    "GroundedInteger",
    "GroundedRational",
    "SurrealNumber",
    "are_equivalent_cauchy",
    "derivative_quotient",
    "riemann_integral",
    "symbolic_polynomial_derivative",
    "symbolic_polynomial_integral",
    # Meta Features
    "Abstraction",
    "abstract",
    "deobjectify_apg",
    "deobjectify_function",
    "deobjectify_relation",
    "fractal_hyperset",
    "meta_fractalize",
    "objectify_apg",
    "objectify_function",
    "objectify_relation",
    "unfold_step",
]
